services:
  mcp-bridge:
    build:
      context: .
    develop:
      watch:
        - path: mcp_bridge
          action: rebuild
    container_name: mcp-bridge
    ports:
      - "8000:8000"
    environment:
      - MCP_BRIDGE__INFERENCE_SERVER__BASE_URL=
      - MCP_BRIDGE__INFERENCE_SERVER__API_KEY=
    # volumes:
    #   - ./config.json:/mcp_bridge/config.json
    restart: unless-stopped
